title: Bakker Lab
first_name: Michael
middle_name: 
last_name: Bakker
email: 
description: Research website by Michael Bakker
keywords: computational pharmacy, high-throughput-simulation, machine-learning, explainable artificial intelligence, Eugen Hruska  # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: # flavicon.ico  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

