title: Bakker Lab
first_name: Michael
middle_name: 
last_name: Bakker
email: 
description: Research website by Michael Bakker
keywords: computational pharmacy, high-throughput-simulation, machine-learning, explainable artificial intelligence, Eugen Hruska  # add your own keywords or leave empty
